#page title
page_title                                : iKPOP Fan Zone                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1606439200                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/app/ikpop-fan-zone/id1606439200                                       # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/logo.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : iKPOP                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : iKPOP, links for you to support your faves and stan all the way. Vote and promote your bias. Earn rewards for your favourite idols together with fans from around the globe.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : iKPOP Fan Zone                                
your_link                                 : https://ikpop.club/app                     
your_city                                 :                                 
email_address                             : ikpop.app@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : ikpop_twt
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : iKPOP. Designed For You. üåé 
    description                           : Are you a K-POP or J-POP fan? Have fun with iKPOP real time platform. Everything you need to stan your favorite idols.
    fontawesome_icon_name                 : globe-americas
    
  - title                                 : Diamond of Diamonds üíé
    description                           : Collect free diamonds. The most dedicated fans can win rewards for their favourite idols together with the fans around the globe!
    fontawesome_icon_name                 : gem

  - title                                 : Vote üó≥Ô∏è 
    description                           : Vote and see ranking changes in real time. <br>Win. Support. Celebrate...
    fontawesome_icon_name                 : vote-yea


  - title                                 : Support üíó
    description                           : Create and promote Fan Events dedicated for your idol. 
    fontawesome_icon_name                 : hand-holding-heart

  - title                                 : RealTime. Fast. Free. üöÄ
    description                           : Voting, Rankings, Charts, Statistics, Fan Events - all in real time.
    fontawesome_icon_name                 : mobile
  
  - title                                 : Celebrate üéâ
    description                           : Celebrate your idol birthday, debut anniversary, new album release in a special way. 
    fontawesome_icon_name                 : gifts

  - title                                 : Promote üìà
    description                           : Share your passion with the world. Share voting certificates, idol profiles and more...
    fontawesome_icon_name                 : share-alt

  - title                                 : Have fun üí¨
    description                           : Chat with other fans in real time. Earn badges and boosters. Take quizes.
    fontawesome_icon_name                 : users

  - title                                 : Enjoy ‚ú®
    description                           : Every action you take is reflected in your bias monthly and annual ranking. Even predebut groups/auditions are included.
    fontawesome_icon_name                 : medal

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
